# Generated by Django 2.0.7 on 2018-07-11 18:21

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Alias', models.CharField(max_length=70, unique=True)),
                ('Description', models.TextField()),
            ],
            options={
                'verbose_name': 'Категории',
                'verbose_name_plural': 'Категория',
            },
        ),
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Alias', models.CharField(max_length=70, unique=True)),
                ('Page_Text', models.TextField()),
                ('Page_Date', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Страницы',
                'verbose_name_plural': 'Страница',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('alias', models.CharField(max_length=70, unique=True)),
                ('text', ckeditor.fields.RichTextField()),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Category')),
            ],
            options={
                'verbose_name': 'Посты',
                'verbose_name_plural': 'Пост',
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Blog_Title', models.CharField(max_length=100)),
                ('Blog_Description', models.CharField(max_length=200)),
                ('Blog_Logo', models.FileField(upload_to='')),
                ('Create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Настройки',
                'verbose_name_plural': 'Настройка',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Alias', models.CharField(max_length=70, unique=True)),
                ('Description', models.TextField()),
            ],
            options={
                'verbose_name': 'Тэги',
                'verbose_name_plural': 'Тэг',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(to='blog.Tag'),
        ),
    ]
