# Generated by Django 2.0.7 on 2018-07-11 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='Is_Active',
            field=models.BooleanField(default=None),
        ),
    ]
