# Generated by Django 2.0.7 on 2018-07-11 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_setting_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='Is_Active',
            field=models.NullBooleanField(default=None),
        ),
    ]
