# Generated by Django 2.0.7 on 2018-07-11 19:06

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180711_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='Active',
        ),
        migrations.AddField(
            model_name='setting',
            name='Header_Background',
            field=colorfield.fields.ColorField(default='#CCCCCC', max_length=18),
        ),
        migrations.AddField(
            model_name='setting',
            name='Header_Text_Color',
            field=colorfield.fields.ColorField(default='#FFFFFF', max_length=18),
        ),
        migrations.AddField(
            model_name='setting',
            name='Titles_Color',
            field=colorfield.fields.ColorField(default='#CCCCCC', max_length=18),
        ),
        migrations.AlterField(
            model_name='setting',
            name='Is_Active',
            field=models.BooleanField(default=False),
        ),
    ]
