# Generated by Django 2.1.7 on 2019-03-12 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190312_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='attachments',
        ),
        migrations.AddField(
            model_name='attachments',
            name='thePost',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.Post'),
        ),
    ]
