# Generated by Django 2.1.7 on 2019-03-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_post_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pinn',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
