# Generated by Django 2.1.7 on 2019-03-12 13:06

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_post_pinn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=150)),
                ('Text', ckeditor.fields.RichTextField()),
                ('Section', models.IntegerField(choices=[(1, 'Advantages'), (2, 'Partners'), (0, 'Proclamation')])),
            ],
        ),
        migrations.RemoveField(
            model_name='tag',
            name='Description',
        ),
    ]
