# Generated by Django 2.1.7 on 2019-03-12 14:07

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20190312_1606'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AlterModelOptions(
            name='presentation',
            options={'verbose_name': 'Презентация', 'verbose_name_plural': 'Презентации'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Тэг', 'verbose_name_plural': 'Тэги'},
        ),
        migrations.AddField(
            model_name='presentation',
            name='Cover',
            field=models.ImageField(null=True, storage=django.core.files.storage.FileSystemStorage(location='blog/static/media'), upload_to='pres/'),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='Section',
            field=models.IntegerField(choices=[(2, 'Partners'), (1, 'Advantages'), (0, 'Proclamation')]),
        ),
    ]
