# Generated by Django 2.1.7 on 2019-03-12 14:55

import ckeditor.fields
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20190312_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.Category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='logo',
            field=models.ImageField(blank=True, default=0, storage=django.core.files.storage.FileSystemStorage(location='blog/static/media'), upload_to='logos/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='more',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='blog.Tag'),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='Section',
            field=models.IntegerField(choices=[(0, 'Proclamation'), (2, 'Partners'), (1, 'Advantages')]),
        ),
    ]
