# Generated by Django 2.1.7 on 2019-03-12 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20190312_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presentation',
            name='Section',
        ),
        migrations.AddField(
            model_name='presentation',
            name='Kind',
            field=models.IntegerField(choices=[(0, 'Proclamation'), (1, 'Advantages'), (2, 'Partners')], default='0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='presentation',
            name='Link',
            field=models.URLField(default='-'),
            preserve_default=False,
        ),
    ]
