# Generated by Django 2.1.7 on 2019-03-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20190313_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='TemplateTyp',
            field=models.CharField(choices=[('img', 'Image Galary'), ('cat', 'App Catalog')], default='cat', max_length=3),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='Kind',
            field=models.IntegerField(choices=[(1, 'Advantages'), (2, 'Partners'), (0, 'Proclamation')], default=0),
        ),
    ]
