# Generated by Django 2.1.7 on 2019-03-13 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20190313_1404'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sections',
            old_name='Name',
            new_name='Title',
        ),
        migrations.RemoveField(
            model_name='sections',
            name='TemplateTyp',
        ),
        migrations.AddField(
            model_name='sections',
            name='Kind',
            field=models.CharField(choices=[('img', 'Image Galary'), ('cat', 'App Catalog')], default='cat', max_length=3),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='Kind',
            field=models.IntegerField(choices=[(0, 'Proclamation'), (2, 'Partners'), (1, 'Advantages')], default=0),
        ),
    ]
